component-common/bpelse-plugin/src/main/java/com/sun/jbi/cam/plugins/bpelse/ScopesnapshotController.java
/*
 * BEGIN_HEADER - DO NOT EDIT
 * 
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the "License").  You may not use this file except
 * in compliance with the License.
 *
 * You can obtain a copy of the license at
 * https://open-jbi-components.dev.java.net/public/CDDLv1.0.html.
 * See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * HEADER in each file and include the License file at
 * https://open-jbi-components.dev.java.net/public/CDDLv1.0.html.
 * If applicable add the following below this CDDL HEADER,
 * with the fields enclosed by brackets "[]" replaced with
 * your own identifying information: Portions Copyright
 * [year] [name of copyright owner]
 */

/*
 * @(#)ScopesnapshotController.java 
 *
 * Copyright 2004-2007 Sun Microsystems, Inc. All Rights Reserved.
 * 
 * END_HEADER - DO NOT EDIT
 */

package com.sun.jbi.cam.plugins.bpelse;

import com.sun.jbi.cam.plugins.bpelse.datamodel.Scopesnapshot;
import com.sun.jbi.cam.plugins.bpelse.datamodel.ScopesnapshotPK;
import com.sun.jbi.cam.plugins.bpelse.datamodel.State;
import com.sun.jbi.cam.plugins.bpelse.datamodel.Variable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.annotation.Resource;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;
import javax.persistence.Query;
import javax.transaction.UserTransaction;

/**
 *
 * @author nnahata
 */
@SuppressWarnings("unchecked")
public class ScopesnapshotController {
    
    /** Creates a new instance of ScopesnapshotController */
    public ScopesnapshotController() {
    }

    private Scopesnapshot scopesnapshot;

    private DataModel model;

    @Resource
    private UserTransaction utx;

    //@PersistenceUnit(unitName = "cambpelsePU")
    private EntityManagerFactory emf;

    private EntityManager getEntityManager() {
        return emf.createEntityManager();
    }

    private int batchSize = 20;

    private int firstItem = 0;

    public Scopesnapshot getScopesnapshot() {
        return scopesnapshot;
    }

    public void setScopesnapshot(Scopesnapshot scopesnapshot) {
        this.scopesnapshot = scopesnapshot;
    }

    public DataModel getDetailScopesnapshots() {
        return model;
    }

    public void setDetailScopesnapshots(Collection<Scopesnapshot> m) {
        model = new ListDataModel(new ArrayList(m));
    }

    public String createSetup() {
        this.scopesnapshot = new Scopesnapshot();
        return "scopesnapshot_create";
    }

    public String create() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            em.persist(scopesnapshot);
            utx.commit();
            addSuccessMessage("Scopesnapshot was successfully created.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "scopesnapshot_list";
    }

    public String detailSetup() {
        setScopesnapshotFromRequestParam();
        return "scopesnapshot_detail";
    }

    public String editSetup() {
        setScopesnapshotFromRequestParam();
        return "scopesnapshot_edit";
    }

    public String edit() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            scopesnapshot = em.merge(scopesnapshot);
            utx.commit();
            addSuccessMessage("Scopesnapshot was successfully updated.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "scopesnapshot_list";
    }

    public String destroy() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            Scopesnapshot scopesnapshot = getScopesnapshotFromRequestParam();
            scopesnapshot = em.merge(scopesnapshot);
            em.remove(scopesnapshot);
            utx.commit();
            addSuccessMessage("Scopesnapshot was successfully deleted.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "scopesnapshot_list";
    }

    public Scopesnapshot getScopesnapshotFromRequestParam() {
        EntityManager em = getEntityManager();
        try{
            Scopesnapshot o = (Scopesnapshot) model.getRowData();
            o = em.merge(o);
            return o;
        } finally {
            em.close();
        }
    }

    public void setScopesnapshotFromRequestParam() {
        Scopesnapshot scopesnapshot = getScopesnapshotFromRequestParam();
        setScopesnapshot(scopesnapshot);
    }

    public DataModel getScopesnapshots() {
        EntityManager em = getEntityManager();
        try{
            Query q = em.createQuery("select object(o) from Scopesnapshot as o");
            q.setMaxResults(batchSize);
            q.setFirstResult(firstItem);
            model = new ListDataModel(q.getResultList());
            return model;
        } finally {
            em.close();
        }
    }

    public static void addErrorMessage(String msg) {
        FacesMessage facesMsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, msg, msg);
        FacesContext fc = FacesContext.getCurrentInstance();
        fc.addMessage(null, facesMsg);
    }

    public static void addSuccessMessage(String msg) {
        FacesMessage facesMsg = new FacesMessage(FacesMessage.SEVERITY_INFO, msg, msg);
        FacesContext fc = FacesContext.getCurrentInstance();
        fc.addMessage("successInfo", facesMsg);
    }

    public Scopesnapshot findScopesnapshot(ScopesnapshotPK id) {
        EntityManager em = getEntityManager();
        try{
            Scopesnapshot o = (Scopesnapshot) em.find(Scopesnapshot.class, id);
            return o;
        } finally {
            em.close();
        }
    }

    public javax.faces.model.SelectItem[] getStates() {
        EntityManager em = getEntityManager();
        try{
            List <State> l = (List <State>) em.createQuery("select o from State as o").getResultList();
            SelectItem select[] = new SelectItem[l.size()];
            int i = 0;
            for(State x : l) {
                    select[i++] = new SelectItem(x);
                }
                return select;
        } finally {
            em.close();
        }
    }

    public javax.faces.model.SelectItem[] getVariables() {
        EntityManager em = getEntityManager();
        try{
            List <Variable> l = (List <Variable>) em.createQuery("select o from Variable as o").getResultList();
            SelectItem select[] = new SelectItem[l.size()];
            int i = 0;
            for(Variable x : l) {
                    select[i++] = new SelectItem(x);
                }
                return select;
        } finally {
            em.close();
        }
    }

    public int getItemCount() {
        EntityManager em = getEntityManager();
        try{
            int count = ((Long) em.createQuery("select count(o) from Scopesnapshot as o").getSingleResult()).intValue();
            return count;
        } finally {
            em.close();
        }
    }

    public int getFirstItem() {
        return firstItem;
    }

    public int getLastItem() {
        int size = getItemCount();
        return firstItem + batchSize > size ? size : firstItem + batchSize;
    }

    public int getBatchSize() {
        return batchSize;
    }

    public String next() {
        if (firstItem + batchSize < getItemCount()) {
            firstItem += batchSize;
        }
        return "scopesnapshot_list";
    }

    public String prev() {
        firstItem -= batchSize;
        if (firstItem < 0) {
            firstItem = 0;
        }
        return "scopesnapshot_list";
    }
    
}

component-common/bpelse-plugin/src/main/java/com/sun/jbi/cam/plugins/bpelse/VariableController.java
/*
 * BEGIN_HEADER - DO NOT EDIT
 * 
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the "License").  You may not use this file except
 * in compliance with the License.
 *
 * You can obtain a copy of the license at
 * https://open-jbi-components.dev.java.net/public/CDDLv1.0.html.
 * See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * HEADER in each file and include the License file at
 * https://open-jbi-components.dev.java.net/public/CDDLv1.0.html.
 * If applicable add the following below this CDDL HEADER,
 * with the fields enclosed by brackets "[]" replaced with
 * your own identifying information: Portions Copyright
 * [year] [name of copyright owner]
 */

/*
 * @(#)VariableController.java 
 *
 * Copyright 2004-2007 Sun Microsystems, Inc. All Rights Reserved.
 * 
 * END_HEADER - DO NOT EDIT
 */

package com.sun.jbi.cam.plugins.bpelse;

import com.sun.jbi.cam.plugins.bpelse.datamodel.State;
import com.sun.jbi.cam.plugins.bpelse.datamodel.Variable;
import com.sun.jbi.cam.plugins.bpelse.datamodel.VariablePK;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.annotation.Resource;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;
import javax.persistence.Query;
import javax.transaction.UserTransaction;

/**
 *
 * @author nnahata
 */
@SuppressWarnings("unchecked")
public class VariableController {
    
    /** Creates a new instance of VariableController */
    public VariableController() {
    }

    private Variable variable;

    private DataModel model;

    @Resource
    private UserTransaction utx;

    //@PersistenceUnit(unitName = "cambpelsePU")
    private EntityManagerFactory emf;

    private EntityManager getEntityManager() {
        return emf.createEntityManager();
    }

    private int batchSize = 20;

    private int firstItem = 0;

    public Variable getVariable() {
        return variable;
    }

    public void setVariable(Variable variable) {
        this.variable = variable;
    }

    public DataModel getDetailVariables() {
        return model;
    }

    public void setDetailVariables(Collection<Variable> m) {
        model = new ListDataModel(new ArrayList(m));
    }

    public String createSetup() {
        this.variable = new Variable();
        return "variable_create";
    }

    public String create() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            em.persist(variable);
            utx.commit();
            addSuccessMessage("Variable was successfully created.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "variable_list";
    }

    public String detailSetup() {
        setVariableFromRequestParam();
        return "variable_detail";
    }

    public String editSetup() {
        setVariableFromRequestParam();
        return "variable_edit";
    }

    public String edit() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            variable = em.merge(variable);
            utx.commit();
            addSuccessMessage("Variable was successfully updated.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "variable_list";
    }

    public String destroy() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            Variable variable = getVariableFromRequestParam();
            variable = em.merge(variable);
            em.remove(variable);
            utx.commit();
            addSuccessMessage("Variable was successfully deleted.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "variable_list";
    }

    public Variable getVariableFromRequestParam() {
        EntityManager em = getEntityManager();
        try{
            Variable o = (Variable) model.getRowData();
            o = em.merge(o);
            return o;
        } finally {
            em.close();
        }
    }

    public void setVariableFromRequestParam() {
        Variable variable = getVariableFromRequestParam();
        setVariable(variable);
    }

    public DataModel getVariables() {
        EntityManager em = getEntityManager();
        try{
            Query q = em.createQuery("select object(o) from Variable as o");
            q.setMaxResults(batchSize);
            q.setFirstResult(firstItem);
            model = new ListDataModel(q.getResultList());
            return model;
        } finally {
            em.close();
        }
    }

    public static void addErrorMessage(String msg) {
        FacesMessage facesMsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, msg, msg);
        FacesContext fc = FacesContext.getCurrentInstance();
        fc.addMessage(null, facesMsg);
    }

    public static void addSuccessMessage(String msg) {
        FacesMessage facesMsg = new FacesMessage(FacesMessage.SEVERITY_INFO, msg, msg);
        FacesContext fc = FacesContext.getCurrentInstance();
        fc.addMessage("successInfo", facesMsg);
    }

    public Variable findVariable(VariablePK id) {
        EntityManager em = getEntityManager();
        try{
            Variable o = (Variable) em.find(Variable.class, id);
            return o;
        } finally {
            em.close();
        }
    }

    public javax.faces.model.SelectItem[] getStates() {
        EntityManager em = getEntityManager();
        try{
            List <State> l = (List <State>) em.createQuery("select o from State as o").getResultList();
            SelectItem select[] = new SelectItem[l.size()];
            int i = 0;
            for(State x : l) {
                    select[i++] = new SelectItem(x);
                }
                return select;
        } finally {
            em.close();
        }
    }

    public int getItemCount() {
        EntityManager em = getEntityManager();
        try{
            int count = ((Long) em.createQuery("select count(o) from Variable as o").getSingleResult()).intValue();
            return count;
        } finally {
            em.close();
        }
    }

    public int getFirstItem() {
        return firstItem;
    }

    public int getLastItem() {
        int size = getItemCount();
        return firstItem + batchSize > size ? size : firstItem + batchSize;
    }

    public int getBatchSize() {
        return batchSize;
    }

    public String next() {
        if (firstItem + batchSize < getItemCount()) {
            firstItem += batchSize;
        }
        return "variable_list";
    }

    public String prev() {
        firstItem -= batchSize;
        if (firstItem < 0) {
            firstItem = 0;
        }
        return "variable_list";
    }
    
}

component-common/bpelse-plugin/web/src/tabs/auto-generated/scopesnapshot/Detail.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Detail of Scopesnapshot</title>
    </head>
    <body>
        <f:view>
            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            <h1>Detail of scopesnapshot</h1>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="ScopesnapshotPK:"/>
                    <h:outputText value="#{scopesnapshot.scopesnapshot.scopesnapshotPK}" title="ScopesnapshotPK" />
                    <h:outputText value="Varvalue:"/>
                    <h:outputText value="#{scopesnapshot.scopesnapshot.varvalue}" title="Varvalue" />
                    <h:outputText value="State:"/>
                    <h:outputText value="#{scopesnapshot.scopesnapshot.state}" title="State" />
                    <h:outputText value="Variable:"/>
                    <h:outputText value="#{scopesnapshot.scopesnapshot.variable}" title="Variable" />
                </h:panelGrid>
                <h:commandLink action="scopesnapshot_edit" value="Edit" />
                <br>
                <h:commandLink action="scopesnapshot_list" value="Show All Scopesnapshot"/>
            </h:form>
        </f:view>
    </body>
</html>

component-common/bpelse-plugin/web/src/tabs/auto-generated/scopesnapshot/Edit.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Edit Scopesnapshot</title>
    </head>
    <body>
        <f:view>
            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            <h1>Edit scopesnapshot</h1>
            <h:form>
                <h:inputHidden value="#{scopesnapshot.scopesnapshot}" immediate="true"/>
                <h:panelGrid columns="2">
                    <h:outputText value="ScopesnapshotPK:"/>
                    <h:outputText value="#{scopesnapshot.scopesnapshot.scopesnapshotPK}" title="ScopesnapshotPK" />
                    <h:outputText value="Varvalue:"/>
                    <h:inputText id="varvalue" value="#{scopesnapshot.scopesnapshot.varvalue}" title="Varvalue" />
                    <h:outputText value="State:"/>
                    <h:selectOneMenu id="state" value="#{scopesnapshot.scopesnapshot.state}" title="State">
                        <f:selectItems value="#{scopesnapshot.states}"/>
                    </h:selectOneMenu>
                    <h:outputText value="Variable:"/>
                    <h:selectOneMenu id="variable" value="#{scopesnapshot.scopesnapshot.variable}" title="Variable">
                        <f:selectItems value="#{scopesnapshot.variables}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{scopesnapshot.edit}" value="Save"/>
                <br>
                <h:commandLink action="scopesnapshot_list" value="Show All Scopesnapshot"/>
            </h:form>
        </f:view>
    </body>
</html>

component-common/bpelse-plugin/web/src/tabs/auto-generated/scopesnapshot/List.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>List Scopesnapshot</title>
    </head>
    <body>
        <f:view>
            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            <h1>Listing Scopesnapshots</h1>
            <h:form>
                <h:commandLink action="#{scopesnapshot.createSetup}" value="New Scopesnapshot"/>
                <br>
                <h:outputText value="Item #{scopesnapshot.firstItem + 1}..#{scopesnapshot.lastItem} of #{scopesnapshot.itemCount}"/>&nbsp;
                <h:commandLink action="#{scopesnapshot.prev}" value="Previous #{scopesnapshot.batchSize}" rendered="#{scopesnapshot.firstItem >= scopesnapshot.batchSize}"/>&nbsp;
                <h:commandLink action="#{scopesnapshot.next}" value="Next #{scopesnapshot.batchSize}" rendered="#{scopesnapshot.lastItem + scopesnapshot.batchSize <= scopesnapshot.itemCount}"/>&nbsp;
                <h:commandLink action="#{scopesnapshot.next}" value="Remaining #{scopesnapshot.itemCount - scopesnapshot.lastItem}"
                               rendered="#{scopesnapshot.lastItem < scopesnapshot.itemCount && scopesnapshot.lastItem + scopesnapshot.batchSize > scopesnapshot.itemCount}"/>
                <h:dataTable value='#{scopesnapshot.scopesnapshots}' var='item' border="1" cellpadding="2" cellspacing="0">
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="ScopesnapshotPK"/>
                        </f:facet>
                        <h:commandLink action="#{scopesnapshot.detailSetup}" value="#{item.scopesnapshotPK}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Varvalue"/>
                        </f:facet>
                        <h:outputText value="#{item.varvalue}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="State"/>
                        </f:facet>
                        <h:outputText value="#{item.state}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Variable"/>
                        </f:facet>
                        <h:outputText value="#{item.variable}"/>
                    </h:column>
                    <h:column>
                        <h:commandLink value="Destroy" action="#{scopesnapshot.destroy}">
                            <f:param name="scopesnapshotPK" value="#{item.scopesnapshotPK}"/>
                        </h:commandLink>
                        <h:outputText value=" "/>
                        <h:commandLink value="Edit" action="#{scopesnapshot.editSetup}">
                            <f:param name="scopesnapshotPK" value="#{item.scopesnapshotPK}"/>
                        </h:commandLink>
                    </h:column>
                </h:dataTable>
            </h:form>
        </f:view>
    </body>
</html>

component-common/bpelse-plugin/web/src/tabs/auto-generated/scopesnapshot/New.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>New Scopesnapshot</title>
    </head>
    <body>
        <f:view>
            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            <h1>New scopesnapshot</h1>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="ScopesnapshotPK:"/>
                    <h:inputText id="scopesnapshotPK" value="#{scopesnapshot.scopesnapshot.scopesnapshotPK}" title="ScopesnapshotPK" />
                    <h:outputText value="Varvalue:"/>
                    <h:inputText id="varvalue" value="#{scopesnapshot.scopesnapshot.varvalue}" title="Varvalue" />
                    <h:outputText value="State:" rendered="#{scopesnapshot.scopesnapshot.state == null}"/>
                    <h:selectOneMenu id="state" value="#{scopesnapshot.scopesnapshot.state}" title="State" rendered="#{scopesnapshot.scopesnapshot.state == null}">
                        <f:selectItems value="#{scopesnapshot.states}"/>
                    </h:selectOneMenu>
                    <h:outputText value="Variable:" rendered="#{scopesnapshot.scopesnapshot.variable == null}"/>
                    <h:selectOneMenu id="variable" value="#{scopesnapshot.scopesnapshot.variable}" title="Variable" rendered="#{scopesnapshot.scopesnapshot.variable == null}">
                        <f:selectItems value="#{scopesnapshot.variables}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{scopesnapshot.create}" value="Create"/>
                <br>
                <h:commandLink action="scopesnapshot_list" value="Show All Scopesnapshot"/>
            </h:form>
        </f:view>
    </body>
</html>