component-common/bpelse-plugin/src/main/java/com/sun/jbi/cam/plugins/bpelse/EngineController.java
/*
 * BEGIN_HEADER - DO NOT EDIT
 * 
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the "License").  You may not use this file except
 * in compliance with the License.
 *
 * You can obtain a copy of the license at
 * https://open-jbi-components.dev.java.net/public/CDDLv1.0.html.
 * See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * HEADER in each file and include the License file at
 * https://open-jbi-components.dev.java.net/public/CDDLv1.0.html.
 * If applicable add the following below this CDDL HEADER,
 * with the fields enclosed by brackets "[]" replaced with
 * your own identifying information: Portions Copyright
 * [year] [name of copyright owner]
 */

/*
 * @(#)EngineController.java 
 *
 * Copyright 2004-2007 Sun Microsystems, Inc. All Rights Reserved.
 * 
 * END_HEADER - DO NOT EDIT
 */

package com.sun.jbi.cam.plugins.bpelse;

import com.sun.jbi.cam.plugins.bpelse.datamodel.Engine;
import java.util.ArrayList;
import java.util.Collection;
import javax.annotation.Resource;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;
import javax.persistence.Query;
import javax.transaction.UserTransaction;

/**
 *
 * @author nnahata
 */
@SuppressWarnings("unchecked")
public class EngineController {
    
    /** Creates a new instance of EngineController */
    public EngineController() {
    }

    private Engine engine;

    private DataModel model;

    @Resource
    private UserTransaction utx;

    //@PersistenceUnit(unitName = "cambpelsePU")
    private EntityManagerFactory emf;

    private EntityManager getEntityManager() {
        return emf.createEntityManager();
    }

    private int batchSize = 20;

    private int firstItem = 0;

    public Engine getEngine() {
        return engine;
    }

    public void setEngine(Engine engine) {
        this.engine = engine;
    }

    public DataModel getDetailEngines() {
        return model;
    }

    public void setDetailEngines(Collection<Engine> m) {
        model = new ListDataModel(new ArrayList(m));
    }

    public String createSetup() {
        this.engine = new Engine();
        return "engine_create";
    }

    public String create() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            em.persist(engine);
            utx.commit();
            addSuccessMessage("Engine was successfully created.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "engine_list";
    }

    public String detailSetup() {
        setEngineFromRequestParam();
        return "engine_detail";
    }

    public String editSetup() {
        setEngineFromRequestParam();
        return "engine_edit";
    }

    public String edit() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            engine = em.merge(engine);
            utx.commit();
            addSuccessMessage("Engine was successfully updated.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "engine_list";
    }

    public String destroy() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            Engine engine = getEngineFromRequestParam();
            engine = em.merge(engine);
            em.remove(engine);
            utx.commit();
            addSuccessMessage("Engine was successfully deleted.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "engine_list";
    }

    public Engine getEngineFromRequestParam() {
        EntityManager em = getEntityManager();
        try{
            Engine o = (Engine) model.getRowData();
            o = em.merge(o);
            return o;
        } finally {
            em.close();
        }
    }

    public void setEngineFromRequestParam() {
        Engine engine = getEngineFromRequestParam();
        setEngine(engine);
    }

    public DataModel getEngines() {
        EntityManager em = getEntityManager();
        try{
            Query q = em.createQuery("select object(o) from Engine as o");
            q.setMaxResults(batchSize);
            q.setFirstResult(firstItem);
            model = new ListDataModel(q.getResultList());
            return model;
        } finally {
            em.close();
        }
    }

    public static void addErrorMessage(String msg) {
        FacesMessage facesMsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, msg, msg);
        FacesContext fc = FacesContext.getCurrentInstance();
        fc.addMessage(null, facesMsg);
    }

    public static void addSuccessMessage(String msg) {
        FacesMessage facesMsg = new FacesMessage(FacesMessage.SEVERITY_INFO, msg, msg);
        FacesContext fc = FacesContext.getCurrentInstance();
        fc.addMessage("successInfo", facesMsg);
    }

    public Engine findEngine(String id) {
        EntityManager em = getEntityManager();
        try{
            Engine o = (Engine) em.find(Engine.class, id);
            return o;
        } finally {
            em.close();
        }
    }

    public int getItemCount() {
        EntityManager em = getEntityManager();
        try{
            int count = ((Long) em.createQuery("select count(o) from Engine as o").getSingleResult()).intValue();
            return count;
        } finally {
            em.close();
        }
    }

    public int getFirstItem() {
        return firstItem;
    }

    public int getLastItem() {
        int size = getItemCount();
        return firstItem + batchSize > size ? size : firstItem + batchSize;
    }

    public int getBatchSize() {
        return batchSize;
    }

    public String next() {
        if (firstItem + batchSize < getItemCount()) {
            firstItem += batchSize;
        }
        return "engine_list";
    }

    public String prev() {
        firstItem -= batchSize;
        if (firstItem < 0) {
            firstItem = 0;
        }
        return "engine_list";
    }
    
}

component-common/bpelse-plugin/web/src/tabs/auto-generated/engine/Detail.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Detail of Engine</title>
    </head>
    <body>
        <f:view>
            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            <h1>Detail of engine</h1>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="Id:"/>
                    <h:outputText value="#{engine.engine.id}" title="Id" />
                    <h:outputText value="Location:"/>
                    <h:outputText value="#{engine.engine.location}" title="Location" />
                    <h:outputText value="Expiration:"/>
                    <h:outputText value="#{engine.engine.expiration}" title="Expiration" />
                </h:panelGrid>
                <h:commandLink action="engine_edit" value="Edit" />
                <br>
                <h:commandLink action="engine_list" value="Show All Engine"/>
            </h:form>
        </f:view>
    </body>
</html>

component-common/bpelse-plugin/web/src/tabs/auto-generated/engine/Edit.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Edit Engine</title>
    </head>
    <body>
        <f:view>
            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            <h1>Edit engine</h1>
            <h:form>
                <h:inputHidden value="#{engine.engine}" immediate="true"/>
                <h:panelGrid columns="2">
                    <h:outputText value="Id:"/>
                    <h:outputText value="#{engine.engine.id}" title="Id" />
                    <h:outputText value="Location:"/>
                    <h:inputText id="location" value="#{engine.engine.location}" title="Location" />
                    <h:outputText value="Expiration:"/>
                    <h:inputText id="expiration" value="#{engine.engine.expiration}" title="Expiration" />
                </h:panelGrid>
                <h:commandLink action="#{engine.edit}" value="Save"/>
                <br>
                <h:commandLink action="engine_list" value="Show All Engine"/>
            </h:form>
        </f:view>
    </body>
</html>

component-common/bpelse-plugin/web/src/tabs/auto-generated/engine/List.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>List Engine</title>
    </head>
    <body>
        <f:view>
            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            <h1>Listing Engines</h1>
            <h:form>
                <h:commandLink action="#{engine.createSetup}" value="New Engine"/>
                <br>
                <h:outputText value="Item #{engine.firstItem + 1}..#{engine.lastItem} of #{engine.itemCount}"/>&nbsp;
                <h:commandLink action="#{engine.prev}" value="Previous #{engine.batchSize}" rendered="#{engine.firstItem >= engine.batchSize}"/>&nbsp;
                <h:commandLink action="#{engine.next}" value="Next #{engine.batchSize}" rendered="#{engine.lastItem + engine.batchSize <= engine.itemCount}"/>&nbsp;
                <h:commandLink action="#{engine.next}" value="Remaining #{engine.itemCount - engine.lastItem}"
                               rendered="#{engine.lastItem < engine.itemCount && engine.lastItem + engine.batchSize > engine.itemCount}"/>
                <h:dataTable value='#{engine.engines}' var='item' border="1" cellpadding="2" cellspacing="0">
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Id"/>
                        </f:facet>
                        <h:commandLink action="#{engine.detailSetup}" value="#{item.id}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Location"/>
                        </f:facet>
                        <h:outputText value="#{item.location}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Expiration"/>
                        </f:facet>
                        <h:outputText value="#{item.expiration}"/>
                    </h:column>
                    <h:column>
                        <h:commandLink value="Destroy" action="#{engine.destroy}">
                            <f:param name="id" value="#{item.id}"/>
                        </h:commandLink>
                        <h:outputText value=" "/>
                        <h:commandLink value="Edit" action="#{engine.editSetup}">
                            <f:param name="id" value="#{item.id}"/>
                        </h:commandLink>
                    </h:column>
                </h:dataTable>
            </h:form>
        </f:view>
    </body>
</html>

component-common/bpelse-plugin/web/src/tabs/auto-generated/engine/New.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>New Engine</title>
    </head>
    <body>
        <f:view>
            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            <h1>New engine</h1>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="Id:"/>
                    <h:inputText id="id" value="#{engine.engine.id}" title="Id" />
                    <h:outputText value="Location:"/>
                    <h:inputText id="location" value="#{engine.engine.location}" title="Location" />
                    <h:outputText value="Expiration:"/>
                    <h:inputText id="expiration" value="#{engine.engine.expiration}" title="Expiration" />
                </h:panelGrid>
                <h:commandLink action="#{engine.create}" value="Create"/>
                <br>
                <h:commandLink action="engine_list" value="Show All Engine"/>
            </h:form>
        </f:view>
    </body>
</html>