component-common/bpelse-plugin/src/main/java/com/sun/jbi/cam/plugins/bpelse/BPInstancesBean.java
/*
 * BEGIN_HEADER - DO NOT EDIT
 * 
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the "License").  You may not use this file except
 * in compliance with the License.
 *
 * You can obtain a copy of the license at
 * https://open-jbi-components.dev.java.net/public/CDDLv1.0.html.
 * See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * HEADER in each file and include the License file at
 * https://open-jbi-components.dev.java.net/public/CDDLv1.0.html.
 * If applicable add the following below this CDDL HEADER,
 * with the fields enclosed by brackets "[]" replaced with
 * your own identifying information: Portions Copyright
 * [year] [name of copyright owner]
 */

/*
 * @(#)BPInstancesBean.java 
 *
 * Copyright 2004-2007 Sun Microsystems, Inc. All Rights Reserved.
 * 
 * END_HEADER - DO NOT EDIT
 */

package com.sun.jbi.cam.plugins.bpelse;

import com.sun.jbi.cam.plugins.bpelse.table.util.Group;
import com.sun.webui.jsf.component.Table;
import com.sun.webui.jsf.component.TableRowGroup;

import com.sun.data.provider.TableDataProvider;
import com.sun.data.provider.impl.ObjectListDataProvider;

import com.sun.jbi.cam.plugins.bpelse.datamodel.State;
import com.sun.jbi.cam.plugins.bpelse.StateController;
        
import com.sun.jbi.cam.plugins.bpelse.table.util.Dynamic;
import com.sun.jbi.cam.plugins.bpelse.table.util.Filter;
        
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author nnahata
 */
@SuppressWarnings("unchecked")
public class BPInstancesBean {
        
    private Dynamic dynamic = null; // Dynamic util.
    
    private Table table = null; // Table component.
    private TableRowGroup rowGroup1 = null;
    private TableDataProvider provider = null; // Data provider.
    private TableDataProvider statesProvider = null; // Data provider.
    
    private Filter filter = null;    
    
    public List<State> states = null;
    public List<BPInstance> instances = null;
    private List<String> listColNames=null;
    private List<String> listColValExprs=null;

    private Group groupA = null; 
    
    /** Creates a new instance of BPInstancesTableBean */
    public BPInstancesBean() {
         //filter = new Filter(this);
         dynamic = new Dynamic();
         
         initDummyData();
         provider = new ObjectListDataProvider(instances);
    }

    
    
    public Filter getFilter(){
        return filter;
    }
    
    public TableDataProvider getInstances(){
        return provider;
    }
     

    public TableRowGroup getTableRowGroup(){
        return rowGroup1;
    }
    
    // Get Table component.
    public Table getTable() {
        if (table == null) {
            rowGroup1 = dynamic.getTableRowGroup("BPInstancesRowGroup",
                "#{BPInstancesBean.instances}", null);
            
            //dynamic.setTableRowGroupChildren(rowGroup1, mapTableColsExprs);
            dynamic.setTableRowGroupChildren(rowGroup1, 
                    null,
                    null,
                    listColNames, listColValExprs);
            
            // Get table.
            table = dynamic.getTable("table1", "BPEL Instances");
            table.getChildren().add(rowGroup1);
        }
        return table;
    }

        // Get Table component.
    public Table getStatesTable() {
        if (table == null) {
            rowGroup1 = dynamic.getTableRowGroup("BPInstancesRowGroup",
                "#{state.states}", null);
//            
//            rowGroup1 = dynamic.getTableRowGroup("BPInstancesRowGroup",
//                "#{BPInstancesBean.states}", null);
            
            listColNames = new ArrayList<String>();
            listColValExprs = new ArrayList<String>();

            listColNames.add("ID");
            listColNames.add("ENGINE");
            listColNames.add("STATUS");
            listColNames.add("BPEL");

            listColValExprs.add("#{bpinstance.value.id}");
            listColValExprs.add("#{bpinstance.value.engineid}");
            listColValExprs.add("#{bpinstance.value.status}");
            listColValExprs.add("#{bpinstance.value.bpelid}");
            
            dynamic.setTableRowGroupChildren(rowGroup1, 
                    null,
                    null,
                    listColNames, listColValExprs);
            
            // Get table.
            table = dynamic.getTable("table1", "BPEL Instances");
            table.getChildren().add(rowGroup1);
        }
        return table;
    }
    // Set Table component.
    //
    // @param table The Table component.
    public void setTable(Table table) {
        this.table = table;
    } 
    
    public void setStatesTable(Table table) {
        this.table = table;
    } 
    
    public Group getGroupA() {
        if (groupA != null) {
            return groupA;
        }
        // Create List with all names.
        ArrayList newNames = new ArrayList();
        for (int i = instances.size() - 1; i >= 0; i--) {
            newNames.add(instances.get(i));
        }
        return (groupA = new Group(newNames));
    }
    
    // Reset values so next visit starts fresh.
    private void reset() {
        table = null;
        dynamic = new Dynamic();
    }
    
    private List<BPInstance> getBPInstances(){
        //dummy BP instances
        List<BPInstance> dummyInstances = new ArrayList<BPInstance>();        
        String[] varValues1 = new String[] {"1_value1","1_value2", "1_value3"};
        String[] varValues2 = new String[] {"2_value1","2_value2", "2_value3"};
        
        BPInstance bp1 = new BPInstance("1", "1_attr1", "1_attr2", varValues1);
        BPInstance bp2 = new BPInstance("2", "2_attr1", "2_attr2", varValues2);
        
        dummyInstances.add(bp1);
        dummyInstances.add(bp2);
        
        return dummyInstances;
    }
    
    private void initDummyData(){
        instances = getBPInstances();

        listColNames = new ArrayList<String>();
        listColValExprs = new ArrayList<String>();
        
        listColNames.add("id");
        listColNames.add("attr1");
        listColNames.add("attr2");
        
        listColValExprs.add("#{bpinstance.value.id}");
        listColValExprs.add("#{bpinstance.value.attr1}");
        listColValExprs.add("#{bpinstance.value.attr2}");
        
        //number of dynamic cols
        int numVars = instances.get(0).getVarValues().length;
        
        for(int i =0; i<numVars; i++){
            String varName = "dynamicVar" + (i +1);
            listColNames.add(varName);
            String varValExpr = "#{bpinstance.value.varValues[" + i +"]}";
            listColValExprs.add(varValExpr);
        }
        
    }
    
}

component-common/bpelse-plugin/src/main/java/com/sun/jbi/cam/plugins/bpelse/StateController.java
/*
 * BEGIN_HEADER - DO NOT EDIT
 * 
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the "License").  You may not use this file except
 * in compliance with the License.
 *
 * You can obtain a copy of the license at
 * https://open-jbi-components.dev.java.net/public/CDDLv1.0.html.
 * See the License for the specific language governing
 * permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL
 * HEADER in each file and include the License file at
 * https://open-jbi-components.dev.java.net/public/CDDLv1.0.html.
 * If applicable add the following below this CDDL HEADER,
 * with the fields enclosed by brackets "[]" replaced with
 * your own identifying information: Portions Copyright
 * [year] [name of copyright owner]
 */

/*
 * @(#)StateController.java 
 *
 * Copyright 2004-2007 Sun Microsystems, Inc. All Rights Reserved.
 * 
 * END_HEADER - DO NOT EDIT
 */

package com.sun.jbi.cam.plugins.bpelse;

import com.sun.jbi.cam.plugins.bpelse.datamodel.State;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.annotation.Resource;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.transaction.UserTransaction;

import com.sun.data.provider.TableDataProvider;
import com.sun.data.provider.impl.ObjectListDataProvider;
import com.sun.data.provider.RowKey;
import com.sun.data.provider.FieldKey;
import com.sun.jbi.cam.common.GenericConstants;
import com.sun.jbi.cam.plugins.bpelse.table.util.Filter;
import com.sun.jbi.cam.plugins.bpelse.table.util.Group;
import com.sun.jbi.cam.plugins.bpelse.table.util.Select;
import com.sun.webui.jsf.component.TableRowGroup;
import javax.faces.context.ExternalContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
/**
 *
 * @author nnahata
 */
@SuppressWarnings("unchecked")
public class StateController {
    
    private State state;

    private DataModel model;
    
    @Resource
    private UserTransaction utx;

    //@PersistenceUnit(unitName = "cambpelsePU")
    private EntityManagerFactory emf;

    /*
    private Dynamic dynamic = null; // Dynamic util.
    private Table table = null; // Table component.
    private List<String> listColNames=null;
    private List<String> listColValExprs=null;
*/
    
    private TableRowGroup rowGroup = null;
    private TableDataProvider provider = null; // Data provider.
    //private Filter filter = null;
    
    public List<State> states = null;
    
    private int batchSize = 20;

    private int firstItem = 0;
    
    private Group groupA = null;
    private Filter groupAFilter = null;
    
    private DBManager dbManager = null;
    
    /** Creates a new instance of StateController */
    public StateController() {
        groupA = new Group(this);
        groupAFilter = new Filter(groupA);
        //dynamic = new Dynamic();
        
        dbManager = new DBManager();
    }
   
    
    public Group getGroupA(){
        if (groupA != null ){
            return groupA;
        }
        
        groupA = new Group(this);
        groupAFilter = new Filter(groupA);
        return groupA;
        
    }
   
    public Filter getGroupAFilter(){
        return groupAFilter;
    }       
    
    private EntityManager getEntityManager() {
        return emf.createEntityManager();
    }

    public State getState() {
        return state;
    }

    public void setState(State state) {
        this.state = state;
    }

    public DataModel getDetailStates() {
        return model;
    }

    public void setDetailStates(Collection<State> m) {
        model = new ListDataModel(new ArrayList(m));
    }

    public String createSetup() {
        this.state = new State();
        return "state_create";
    }

    public String create() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            em.persist(state);
            utx.commit();
            addSuccessMessage("State was successfully created.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "state_list";
    }

    public String detailSetup() {
        setStateFromRequestParam();
        return "state_detail";
    }

    public String editSetup() {
        setStateFromRequestParam();
        return "state_edit";
    }

    public String edit() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            state = em.merge(state);
            utx.commit();
            addSuccessMessage("State was successfully updated.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "state_list";
    }

    public String destroy() {
        EntityManager em = getEntityManager();
        try {
            utx.begin();
            State state = getStateFromRequestParam();
            state = em.merge(state);
            em.remove(state);
            utx.commit();
            addSuccessMessage("State was successfully deleted.");
        } catch (Exception ex) {
            try {
                addErrorMessage(ex.getLocalizedMessage());
                utx.rollback();
            } catch (Exception e) {
                addErrorMessage(e.getLocalizedMessage());
            }
        } finally {
            em.close();
        }
        return "state_list";
    }

    public State getStateFromRequestParam() {
        EntityManager em = getEntityManager();
        try{
            State o = (State) model.getRowData();
            o = em.merge(o);
            return o;
        } finally {
            em.close();
        }
    }

    public void setStateFromRequestParam() {
        State state = getStateFromRequestParam();
        setState(state);
    }

/*
    public TableDataProvider getStates() {
     System.out.println(">>>>Using ENTITY MANAGER for getting states");
//        if (provider != null ){
//            return provider;
//        }
        
        EntityManager em = getEntityManager();
        try{
            Query q = em.createQuery("select object(o) from State as o");
            q.setMaxResults(batchSize);
            q.setFirstResult(firstItem);
            //model = new ListDataModel(q.getResultList());
            //return model;
            
             provider = new ObjectListDataProvider(q.getResultList());
//            return q.getResultList();
        } catch(Throwable exception) {
            // Catch the org.apache.derby.client.am.SqlException Runtime 
            // exception thrown by the data layer.
            // This prevents a bad 500 error message in the Web App Servlet, i.e.,
            // javax.servlet.ServletException: Schema 'BPELSE_SCHEMA' does not exist
            // if the BPEL Schema is not created and ensures graceful behavior 
            // of the Web Application.
            exception.printStackTrace();
        } finally {
            em.close();
        }
        return provider;
    }
*/
   
    public TableDataProvider getStates(){
        System.out.println(">>>> Using DBManager for getting states");
        String suName = null;
        // update service unit name
        FacesContext context = FacesContext.getCurrentInstance();
        ExternalContext ex = context.getExternalContext();
        HttpServletRequest request = (HttpServletRequest)ex.getRequest();
        HttpSession session = request.getSession();  
        String viewType = 
                (String)session.getAttribute(GenericConstants.COMPONENT_TYPE);
        if(viewType.equals(GenericConstants.SU_TYPE)) {
            String name = 
              (String)session.getAttribute(GenericConstants.COMPONENT_NAME);
            String parentName = 
              (String)session.getAttribute(GenericConstants.COMPONENT_PNAME);
            suName = parentName + "-" + name;
        }
        provider = new ObjectListDataProvider(dbManager.getBPInstances(suName));
        return provider;
    }
   
    public TableDataProvider getNumericVars(){
    	TableDataProvider varprovider = new ObjectListDataProvider(dbManager.getNumericVars("BPEL_ID_0"));
        return varprovider;
    }
   
    /*
    public Table getTable() {
        if (table == null) {
            rowGroup = dynamic.getTableRowGroup("BPInstancesRowGroup",
                "#{state.states}", null);
            
            dynamic.setValueBinding(rowGroup,"binding","#{state.tableRowGroup}");
            
            listColNames = new ArrayList<String>();
            listColValExprs = new ArrayList<String>();

            listColNames.add("ID");
            listColNames.add("ENGINE");
            listColNames.add("STATUS");
            listColNames.add("BPEL");

            listColValExprs.add("#{bpinstance.value.id}");
            listColValExprs.add("#{bpinstance.value.engineid}");
            listColValExprs.add("#{bpinstance.value.status}");
            listColValExprs.add("#{bpinstance.value.bpelid}");
            
            dynamic.setTableRowGroupChildren(rowGroup, 
                    null,
                    null,
                    listColNames, listColValExprs);
            
            // Get table.
            table = dynamic.getTable("table1", "BPEL Instances");
            table.getChildren().add(rowGroup);
        }

component-common/bpelse-plugin/web/src/tabs/actionsTop.jsp
<jsp:root version="1.2" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:webuijsf="http://www.sun.com/webui/webuijsf">
  <jsp:directive.page contentType="text/html" />

<!-- Actions (Top) -->
<webuijsf:button id="deleteselected"
    actionExpression="#{state.deleteSelected}"
    disabled="#{state.deleteSelectedDisabled}"
    onClick="if (confirmDeleteSelectedRows() == false) return false"
    text="#{msgs.bpelse_instances_delete_selected}"
    toolTip="#{msgs.bpelse_instances_delete_selected_tip}"/>
</jsp:root>

component-common/bpelse-plugin/web/src/tabs/filterPanel.jsp
<jsp:root version="1.2" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:webuijsf="http://www.sun.com/webui/webuijsf">
  <jsp:directive.page contentType="text/html" />

<!-- Filter Panel -->
<webuijsf:staticText id="statictext1" text="Show only rows with: " /> 
<br />
<webuijsf:textField id="customFilter"
    columns="50"
    label="#{bptablemsgs.table_customFilterLabel_STATUS}"
    labelLevel="2"
    onKeyPress="if (event.keyCode==13) {var e=document.getElementById('form1:table1:filterPanel:submit'); if (e != null) e.click(); return false}"
    text="#{state.groupAFilter.statusCustomFilter}"/>
<webuijsf:textField id="customFilterBpelID"
    columns="50"
    label="#{bptablemsgs.table_customFilterLabel_BPELID}"
    labelLevel="2"
    onKeyPress="if (event.keyCode==13) {var e=document.getElementById('form1:table1:filterPanel:submit'); if (e != null) e.click(); return false}"
    text="#{state.groupAFilter.bpelIdCustomFilter}"/>
<div class="TblPnlBtnDiv">
  <webuijsf:button id="submit"
      actionExpression="#{state.groupAFilter.applyCustomFilter}"
      mini="true"
      primary="true"
      text="#{bptablemsgs.table_ok}"/>
  <webuijsf:button id="cancel"
      mini="true"
      onClick="toggleFilterPanel(); return false"
      text="#{bptablemsgs.table_cancel}"/>
</div>

<!-- Note: If the user presses the enter key while the text field has focus,
     the page will be submitted incorrectly, unless we capture the onKeyPress
     event and invoke the click method of the submit button. -->

</jsp:root>

component-common/bpelse-plugin/web/src/tabs/instances.jsp
<?xml version="1.0" encoding="UTF-8"?>

<jsp:root version="1.2" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:webuijsf="http://www.sun.com/webui/webuijsf">

    <jsp:directive.page contentType="text/html;charset=ISO-8859-1" pageEncoding="UTF-8"/>
    
    <f:view>
        <webuijsf:page frame="true">
            <webuijsf:html>
                <webuijsf:head title="Composite Application Manager" />
                <webuijsf:frameSet id="bpInstancesSvgFrameSet"  rows="50%,*"  >
                     <webuijsf:frame name="svgFrame" frameBorder="false" url="/faces/tabs/svg.jsp"  noResize="false"/>
                     <webuijsf:frame name="instancesFrame" toolTip="topFrame" url="/faces/tabs/instancesTable.jsp" frameBorder="false" noResize="true" scrolling="false" />
                </webuijsf:frameSet>

                
            </webuijsf:html>
        </webuijsf:page>
    </f:view>

</jsp:root>


<!--
<jsp:root version="1.2" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:webuijsf="http://www.sun.com/webui/webuijsf">

    <jsp:directive.page contentType="text/html;charset=ISO-8859-1" pageEncoding="UTF-8"/>
    
    <f:view>
        <webuijsf:page frame="true">
            <webuijsf:html>
                <f:loadBundle basename="com.sun.jbi.cam.common.resources.Bundle" var="msgs" />
                <webuijsf:head title="#{msgs.generic_Statistics}" />
                <webuijsf:panelGroup id="myPanelGroup1">
                    <webuijsf:table id="bpInstances_table" binding="#{BPInstancesBean.table}"/>
                </webuijsf:panelGroup>
            </webuijsf:html>
        </webuijsf:page>
    </f:view>

</jsp:root>
-->

component-common/bpelse-plugin/web/src/tabs/simplevars.jsp
<?xml version="1.0" encoding="UTF-8"?>

<jsp:root version="1.2" xmlns:f="http://java.sun.com/jsf/core" 
xmlns:h="http://java.sun.com/jsf/html" 
xmlns:jsp="http://java.sun.com/JSP/Page" 
xmlns:webuijsf="http://www.sun.com/webui/webuijsf">

    <jsp:directive.page contentType="text/html;charset=ISO-8859-1" pageEncoding="UTF-8"/>
    
    <f:view>
        <webuijsf:page frame="true">
            <webuijsf:html>
                <f:loadBundle basename="com.sun.jbi.cam.plugins.bpelse.common.resources.Bundle" var="msgs" />
                <f:loadBundle basename="com.sun.jbi.cam.plugins.bpelse.table.resources.Bundle" var="bptablemsgs" />
                
                 <webuijsf:head title="BPEL Instances">
                      <webuijsf:script url="js/select.js"/>
                      <webuijsf:script url="js/filter.js"/>
                 </webuijsf:head>
                 
                 <webuijsf:form id="form1">
                    <webuijsf:contentPageTitle id="pagetitle" title="BPEL Instances" helpText="Table below shows a list of Business Process Instances" />
                    <br />
                    <div class="ConMgn"> 
                        
              <!-- Instances Table -->
              <webuijsf:table id="table1"
                deselectMultipleButton="true"
                deselectMultipleButtonOnClick="setTimeout('disableActions()', 0)"
                paginateButton="true"
                paginationControls="true"
                selectMultipleButton="true"
                selectMultipleButtonOnClick="setTimeout('disableActions()', 0)"
                title="BPEL Instances">
                <webuijsf:tableRowGroup id="rowGroup1"
                  binding="#{state.groupA.tableRowGroup}"
                  rows="5"
                  selected="#{state.groupA.select.selectedState}"
                  sourceData="#{state.groupA.numericVars}"
                  sourceVar="var">
                  <webuijsf:tableColumn id="col0"
                    selectId="select"
                    sort="#{state.groupA.select.selectedState}">
                    <webuijsf:checkbox id="select"
                      onClick="setTimeout('initAllRows(); disableActions()', 0)"
                      selected="#{state.groupA.select.selected}"
                      selectedValue="#{state.groupA.select.selectedValue}"/>
                  </webuijsf:tableColumn>
                  <webuijsf:tableColumn id="col1" 
                    alignKey="id" headerText="BP Id" rowHeader="true">
                    <webuijsf:staticText text="#{var.value.bpid}"/>
                  </webuijsf:tableColumn>
                  <webuijsf:tableColumn id="col2" alignKey="varid" headerText="Var Id">
                    <webuijsf:staticText text="#{var.value.id}"/>
                  </webuijsf:tableColumn>
                  <webuijsf:tableColumn id="col3" alignKey="value" headerText="Value">
                    <webuijsf:staticText text="#{var.value.numericValue}"/>
                  </webuijsf:tableColumn>
                </webuijsf:tableRowGroup>

                <!--
                <f:facet name="actionsTop">
                  <f:subview id="actionsTop">
                    <jsp:include page="actionsTop.jsp"/>
                  </f:subview>
                </f:facet>
                <f:facet name="actionsBottom">
                  <f:subview id="actionsBottom">
                    <jsp:include page="actionsBottom.jsp"/>
                  </f:subview>
                </f:facet>
                -->
                
                <!-- Filter -->
                <f:facet name="filter">
                  <webuijsf:dropDown submitForm="true" id="filter"
                    actionExpression="#{state.groupAFilter.applyBasicFilter}" 
                    items="#{state.groupAFilter.filterOptions}"
                    onChange="if (filterMenuChanged() == false) return false"
                    selected="#{state.groupAFilter.basicFilter}"/>
                </f:facet>
                <!-- Filter Panel -->
                <f:facet name="filterPanel">
                  <f:subview id="filterPanel">
                    <jsp:include page="filterPanel.jsp"/>
                  </f:subview>
                </f:facet>                
              </webuijsf:table>

                        <!--
                        <webuijsf:table id="table1" binding="#{state.table}" 
                            filterPanelFocusId="form1:table1:filterPanel:customFilter_field"
                            filterText="#{state.groupA.filter.filterText}"
                            width="95%">
                      
                            <f:facet name="filter">
                              <webuijsf:dropDown submitForm="true" id="filter"
                                actionExpression="#{state.groupA.filter.applyBasicFilter}" 
                                items="#{state.groupA.filter.filterOptions}"
                                onChange="if (filterMenuChanged() == false) return false"
                                selected="#{state.groupA.filter.basicFilter}"/>
                            </f:facet>
                            
                      
                            <f:facet name="actionsTop">
                              <f:subview id="actionsTop">
                                <jsp:include page="actionsTop.jsp"/>
                              </f:subview>
                            </f:facet>
                      
                            <f:facet name="filterPanel">
                              <f:subview id="filterPanel">
                                <jsp:include page="filterPanel.jsp"/>
                              </f:subview>
                            </f:facet>
                      </webuijsf:table>
                      -->

                    </div>
                </webuijsf:form>
            </webuijsf:html>
        </webuijsf:page>
    </f:view>

</jsp:root>

component-common/bpelse-plugin/web/src/tabs/svg.jsp
<?xml version="1.0" encoding="UTF-8"?>

<jsp:root version="1.2" 
 xmlns:f="http://java.sun.com/jsf/core" 
 xmlns:h="http://java.sun.com/jsf/html" 
 xmlns:jsp="http://java.sun.com/JSP/Page" 
 xmlns:webuijsf="http://www.sun.com/webui/webuijsf">

    <jsp:directive.page contentType="text/html;charset=ISO-8859-1" pageEncoding="UTF-8"/>
    
    <f:view>
        <webuijsf:page>
            <webuijsf:html>
                <webuijsf:head title="Composite Application Manager" />
                <webuijsf:contentPageTitle id="pagetitle" title="SVG" helpText="" />
            </webuijsf:html>
        </webuijsf:page>
    </f:view>

</jsp:root>

component-common/bpelse-plugin/web/src/tabs/tabs.jsp
<?xml version="1.0" encoding="UTF-8"?>

<jsp:root version="1.2" xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:jsp="http://java.sun.com/JSP/Page" xmlns:webuijsf="http://www.sun.com/webui/webuijsf">

    <jsp:directive.page contentType="text/html;charset=ISO-8859-1" pageEncoding="UTF-8"/>
    
    <f:view>
        <webuijsf:page frame="true">
            <webuijsf:html>

            <webuijsf:form id="form1"> 

                <f:loadBundle basename="com.sun.jbi.cam.plugins.bpelse.common.resources.Bundle" var="msgs" />
                <webuijsf:head title="Composite Application Manager" />

                <webuijsf:tabSet id="tabs" selected="tabBlank" binding="#{BPTabsBean.tabSet}">
                    <!---
                    <webuijsf:tab id="tabBlank" text="" url="http://www.sun.com" target="tabBottomFrame" />                    
                    
                    <webuijsf:tab id="tabStatistics" text="#{msgs.generic_Statistics}" url="/faces/manager/framework/generic/statistics.jsp" target="tabBottomFrame" />
                    <webuijsf:tab id="tabControl" text="#{msgs.generic_Control}"  url="/faces/manager/framework/generic/control.jsp" target="tabBottomFrame" />
                    <webuijsf:tab id="tabConfiguration" text="#{msgs.generic_Configuration}" url="/faces/manager/framework/generic/configuration.jsp" target="tabBottomFrame" />
                    <webuijsf:tab id="tabBPInstances" text="#{msgs.bpelse_instances_tab_title}" url="/faces/plugins/bpelse/instancesTable.jsp" target="tabBottomFrame" />                    
                    -->    
                </webuijsf:tabSet >                

            </webuijsf:form> 

            </webuijsf:html>
        </webuijsf:page>
    </f:view>

</jsp:root>